# Generated by Django 6.0.3 on 2026-07-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_register_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='confirm_password',
            field=models.CharField(max_length=100),
        ),
    ]
