# Generated by Django 6.0.3 on 2026-07-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_register_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='confirm_password',
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
