# Generated by Django 6.0.3 on 2026-07-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_register_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
